### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI3428#12]
Buttons on the Mobile App Development system are styled the same throughout the application. This means we can create one reusable component for all the similar buttons.

- The button component should be styled similarly to the image below
- The custom button component could be called `CustomButton.js` and live in a `/components` directory
- The button should take 2 props: label, and a handlePress function

Reply, Back, and Help should all have the same Component
<img width="939" alt="Screen Shot 2020-10-11 at 2 21 34 PM" src="https://user-images.githubusercontent.com/57203324/95685385-f44fbe00-0bcd-11eb-946b-cec8e6f0f52a.png">

**Comment by nbhardwaj2208** [comment]
Thanks bro got it
*Thanks & Regards*
*Nikhil Bhardwaj*

**Comment by nickm0rash** [comment]
done - Needs Styling  button.module.css
