### ISSUE TITLE
Compose Validation

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI3428#81]
Certain fields (such as To) require validation on the backend before the email document can be written to the database.

The front-end should reflect these requirements by not letting the user do "bad" things. When a user provides invalid input, the input box can change its styling to a red outline. 

Implement a similar validation form on the `Compose` page as the `CreateAccount` form.
Consider:
- input length
- regex patterns
- other?

**Comment by bivashpandey** [comment]
I guess this is complete. Right?

**Comment by just1ngray** [comment]
You're right. I'll close it for you
